WebSite/Models/ErrorViewModel.cs
using System;

namespace WebSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebSite/Models/Indicacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Models
{
    public class Indicacao
    {
        public int CodigoAssociacao { get; set; }
        public DateTime? DataCriacao { get; set; }
        public string CpfAssociado { get; set; }
        public string EmailAssociado { get; set; }
        public string NomeAssociado { get; set; }
        public string TelefoneAssociado { get; set; }
        public string PlacaVeiculoAssociado { get; set; }
        public string NomeAmigo { get; set; }
        public string TelefoneAmigo { get; set; }
        public string EmailAmigo { get; set; }
        public string Observacao { get; set; }

        public string Remetente { get; set; }
        public string[] Copias { get; set; }
    }
}

WebSite/Models/Oficina.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Models
{
    public class Oficina
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string DescricaoCurta { get; set; }
        public string Endereco { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Foto { get; set; }
        public int AvaliacaoUsuario { get; set; }
        public int CodigoAssociacao { get; set; }
        public string Email { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; } 
        public bool Ativo { get; set; }
    }
}

WebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebSite.Models;

namespace WebSite.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebSite/Controllers/IndicacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebSite.Models;
using WebSite.Services;

namespace WebSite.Controllers
{
    public class IndicacaoController : Controller
    {

        private IIndicacaoService IndicacaoService { get; }

        public IndicacaoController(IIndicacaoService indicacaoService)
        {
            IndicacaoService = indicacaoService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Indicacao indicacao)
        {

            var retorno = IndicacaoService.CreateIndicacao(indicacao);

            if (retorno["Sucesso"].ToString() == "")
            {
                ViewData["Error"] = retorno["RetornoErro"]["retornoErro"].ToString();
            }
            else
            {
                ViewData["Sucesso"] = retorno["Sucesso"].ToString();
            }

            ModelState.Clear();
            return View();
        }
    }
}

WebSite/Controllers/OficinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebSite.Models;
using WebSite.Services;

namespace WebSite.Controllers
{
    public class OficinaController : Controller
    {

        private IOficinaService OficinaService { get; }

        public OficinaController(IOficinaService oficinaService)
        {
            OficinaService = oficinaService;
        }

        public IActionResult Index()
        {
            List<Oficina> oficinas = OficinaService.GetAll();

            return View(oficinas);
        }

        public IActionResult Detalhe(int id)
        {

            var oficina = OficinaService.GetOne(id);

            return View(oficina);
        }
    }
}

WebSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/oficinas.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <h3>Consulte oficinas.</h3>
                    <a class="btn btn-default" asp-area="" asp-controller="Oficina" asp-action="Index">
                        <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/amigos.jpeg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    <h3>Indique amigos.</h3>
                    <a class="btn btn-default" asp-area="" asp-controller="Indicacao" asp-action="Index">
                        <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

WebSite/Views/Indicacao/Index.cshtml
@model Indicacao

@{
    ViewData["Title"] = "Indicação de Amigo";
}

@if (ViewData["Sucesso"] != null)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Parabéns!</strong> @ViewData["Sucesso"]
    </div>
}
@if (ViewData["Error"] != null)
{

    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>Erro ao enviar indicação!</strong> @ViewData["Error"]
    </div>
}

<div class="row">
    <form id="formIndicacao" asp-controller="Indicacao" asp-action="Index" method="post">
        <div class="col-xs-12">
            <h5>Dados da Associação</h5>
        </div>

        <div class="form-group">
            <label asp-for="CodigoAssociacao" class="col-md-2 col-sm-12">Codigo da Associação</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="CodigoAssociacao" />
            </div>
        </div>

        <div class="col-xs-12">
            <h5>Dados do Amigo</h5>
        </div>

        <div class="form-group">
            <label asp-for="NomeAmigo" class="col-md-2 col-sm-12">Nome</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="NomeAmigo" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAmigo" class="col-md-2 col-sm-12">Email</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="EmailAmigo" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TelefoneAmigo" class="col-md-2 col-sm-12">Telefone</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="TelefoneAmigo" class="col-md-4 col-sm-6 col-xs-12" />
            </div>
        </div>

        <div class="col-xs-12">
            <h5>Dados do Associado</h5>
        </div>

        <div class="form-group">
            <label asp-for="NomeAssociado" class="col-md-2 col-sm-12">Nome</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="NomeAssociado" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EmailAssociado" class="col-md-2 col-sm-12">Email</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="EmailAssociado" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CpfAssociado" class="col-md-2 col-sm-12">CPF</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="CpfAssociado" class="col-md-4 col-sm-6 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TelefoneAssociado" class="col-md-2 col-sm-12">Telefone</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="TelefoneAssociado" class="col-md-4 col-sm-6 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PlacaVeiculoAssociado" class="col-md-2 col-sm-12">Placa do Veículo</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="PlacaVeiculoAssociado" class="col-md-4 col-sm-6 col-xs-12" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Observacao" class="col-md-2 col-sm-12"></label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <textarea asp-for="Observacao" class="col-sm-12 col-xs-12"></textarea>
            </div>
        </div>
        <div class="col-xs-12">
            <h5>Dados de Envio</h5>
        </div>
        <div class="form-group">
            <label asp-for="Remetente" class="col-md-2 col-sm-12">Remetente</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="Remetente" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Copias" class="col-md-2 col-sm-12">Copias</label>
            <div class="col-md-10 col-sm-12 col-xs-12">
                <input asp-for="Copias" class="col-md-6 col-sm-12 col-xs-12" />
            </div>
        </div>
        <div class="col-xs-12">
            <button type="submit" class="btn btn-primary" role="button">Enviar</button>
        </div>
    </form>
</div>

WebSite/Views/Oficina/Detalhe.cshtml
@model Oficina

@{
    ViewData["Title"] = "Detalhe";
}

<div>
    <div>
        <a asp-action="Index"><span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Voltar para lista</a>
    </div>
    
    <h4>@Model.Nome</h4>
    <p class="lead">@Model.DescricaoCurta</p>
    
    <div class="jumbotron">
        <img src="@Model.Foto" class="img-thumbnail">
        <hr />
        <p>@Html.DisplayFor(model => model.Descricao)</p>
    </div>
    <div>
        <p>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Código da Associação: @Model.CodigoAssociacao
        </p>
        <p>
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
            Endereço: @Model.Endereco
        </p>
        <p>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            Email: @Model.Email
        </p>
        @if (Model.Telefone1 != String.Empty || Model.Telefone2 != String.Empty)
        {
            <p>
                <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                Telefone:<br />
                @Model.Telefone1 <br />
                @Model.Telefone2
            </p>

        }

        <p></p>
    </div>
    <div>
        <div style="width: 100%">
            <iframe width="100%" height="300" src="https://maps.google.com/maps?width=100%&amp;height=300&amp;hl=pt-br&amp;coord=@Model.Latitude,@Model.Longitude&amp;q=@Model.Endereco+(@Model.Nome)&amp;ie=UTF8&amp;t=&amp;z=15&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        </div>
    </div>
</div>

WebSite/Views/Oficina/Index.cshtml
@model List<Oficina>
@{
    ViewData["Title"] = "Oficinas";
}

<div class="row">

    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail" id="thumbnail-oficina">
                <img class="img-oficina-thumbnail" src="@item.Foto" alt="">
                <div class="caption">
                    <h4>@item.Nome</h4>
                    <p>@item.DescricaoCurta</p>
                    <p><a asp-area="" asp-controller="Oficina" asp-action="Detalhe/@item.Id" class="btn btn-primary" role="button">Detalhes</a></p>
                </div>
            </div>
        </div>
    }
</div>

WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebSite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebSite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Início</a></li>
                    <li><a asp-area="" asp-controller="Oficina" asp-action="Index">Consultar Oficinas</a></li>
                    <li><a asp-area="" asp-controller="Indicacao" asp-action="Index">Indicação de Amigo</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebSite</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>